### ISSUE TITLE
Implement compiler checks

### ISSUE THREAD

**Issue by nkakouros** [mal-lang/mal-toolbox#6]
The original mal compiler implemented checks for various aspects of syntax validity, constraints, etc. These can be found [here](https://github.com/mal-lang/malcompiler/blob/master/malcompiler-lib/src/main/java/org/mal_lang/compiler/lib/Analyzer.java).

### TODO
- [ ] Study the mal language. Here are some resources:
  - [ ] https://github.com/mal-lang/mal-documentation/wiki
  - [ ] https://github.com/mal-lang/exampleLang/
- [ ] Understand the new mal compiler:
  - [ ] Study the mal syntax grammar, see [this PR](https://github.com/mal-lang/mal-toolbox/pull/4/files) and the `.g4` grammar file, until it gets merged.
  - [ ] Understand the visitor pattern of the compiler
- [ ] Implement the validator checks
  - [ ] Understand each check in the original compiler's analyzer
  - [ ] Implement each check in the original compiler's analyzer

**Comment by andrewbwm** [comment]
It might be useful for the person doing this to also have a look at the Language Graph(https://github.com/mal-lang/mal-toolbox/blob/main/maltoolbox/language/languagegraph.py).
